### PR TITLE
docs: sample using wildcard for a topic name

### PR DESCRIPTION
**Pull request by gsferreira**
# Description

This is a common question when building consumers: _"How to subscribe to multiple Kafka topics using wildcard patterns?"_

In this sample, it shows how to subscribe to all topics with a given prefix.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have added tests to cover my changes
-   [x] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

**Review by joelfoliveira — COMMENTED** [review]
We can also update the documentation of the Topic method from IConsumerConfigurationBuilder to describe that the parameter topic supports subscribing to multiple topics.

On that note, with the update to the documentation, and since this "feature" is also something shared from the Kafka native client, and not a KafkaFlow specific feature. Do need to include a specific sample demonstrating this functionality?

**Comment by gsferreira** [comment]
> We can also update the documentation of the Topic method from IConsumerConfigurationBuilder to describe that the parameter topic supports subscribing to multiple topics.
> 
> On that note, with the update to the documentation, and since this "feature" is also something shared from the Kafka native client, and not a KafkaFlow specific feature. Do need to include a specific sample demonstrating this functionality?

It's a common question, so, I believe it's useful to explain how to build that using KafkaFlow. Especially considering that the Confluent .NET Client doesn't explain that.

**Comment by joelfoliveira** [comment]
> > We can also update the documentation of the Topic method from IConsumerConfigurationBuilder to describe that the parameter topic supports subscribing to multiple topics.
> > On that note, with the update to the documentation, and since this "feature" is also something shared from the Kafka native client, and not a KafkaFlow specific feature. Do need to include a specific sample demonstrating this functionality?
> 
> It's a common question, so, I believe it's useful to explain how to build that using KafkaFlow. Especially considering that the Confluent .NET Client doesn't explain that.

And what about updating the param documentation to reference that a pattern can be used? Adding that reference could be useful for users using IntelliSense.

**Comment by gsferreira** [comment]
> > > We can also update the documentation of the Topic method from IConsumerConfigurationBuilder to describe that the parameter topic supports subscribing to multiple topics.
> > > On that note, with the update to the documentation, and since this "feature" is also something shared from the Kafka native client, and not a KafkaFlow specific feature. Do need to include a specific sample demonstrating this functionality?
> > 
> > 
> > It's a common question, so, I believe it's useful to explain how to build that using KafkaFlow. Especially considering that the Confluent .NET Client doesn't explain that.
> 
> And what about updating the param documentation to reference that a pattern can be used? Adding that reference could be useful for users using IntelliSense.

@joelfoliveira I'm thinking about adding something simple as the following. What do you say?
```
        /// <summary>
        /// Sets the topic that will be used to read the messages, the partitions will be automatically assigned.
        /// librdkafka patterns are accepted.
        /// </summary>
```

**Comment by gsferreira** [comment]
> > > > We can also update the documentation of the Topic method from IConsumerConfigurationBuilder to describe that the parameter topic supports subscribing to multiple topics.
> > > > On that note, with the update to the documentation, and since this "feature" is also something shared from the Kafka native client, and not a KafkaFlow specific feature. Do need to include a specific sample demonstrating this functionality?
> > > 
> > > 
> > > It's a common question, so, I believe it's useful to explain how to build that using KafkaFlow. Especially considering that the Confluent .NET Client doesn't explain that.
> > 
> > 
> > And what about updating the param documentation to reference that a pattern can be used? Adding that reference could be useful for users using IntelliSense.
> 
> @joelfoliveira I'm thinking about adding something simple as the following. What do you say?
> 
> ```
>         /// <summary>
>         /// Sets the topic that will be used to read the messages, the partitions will be automatically assigned.
>         /// librdkafka patterns are accepted.
>         /// </summary>
> ```

Done ✅

**Review by ruiqbarbosa — APPROVED** [review]

**Pull request merged**
