### PR TITLE
Add MessagePack serializer

### PR DESCRIPTION
**Pull request by JotaDobleEse**
# Description

Add new project KafkaFlow.Serializer.MessagePack that use [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp) library to optimize message sizes.

## How Has This Been Tested?

I tested my changes using Program.cs of KafkaFlow.Sample.FlowControl, I made some changes to use MessagePack instead of NewtonsoftJson locally and runs ok. Also, I've added MessagePackSerializerTests project to unit tests.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

**Comment by gsferreira** [comment]
Hi @JotaDobleEse 

Thank you for taking the time to contribute to KafkaFlow! You are awesome  ⭐️! 

We plan to grow an extension ecosystem and keep the Core project as lean as possible. Since we see value in having MessagePack as a serializer, we kindly ask you if you would like to publish an extension to KafkaFlow on your own. 
You would create a GitHub Repo with the Serializer and publish it as a NuGet package.
Then, we would love to list it under our [Extensions list](https://farfetch.github.io/kafkaflow/extensions).

You can take [KafkaFlow Retry Extensions](https://github.com/Farfetch/kafkaflow-retry-extensions) as an example.

Let us know if you would like to move forward with it. We are more than happy to help you out.

_Before I go, just a recommendation. We recommend opening an issue before a substantial contribution if there isn’t already an issue for the problem you’d like to solve. This helps facilitate a discussion before deciding on an implementation approach._

**Comment by JotaDobleEse** [comment]
Hi @gsferreira, 

Following your recommendations, I have created my own repository and uploaded my package to nuget.org. You can found it [here](https://github.com/JotaDobleEse/kafkaflow-messagepack-serializer).

Greetings!

**Comment by gsferreira** [comment]
That is amazing @JotaDobleEse!
Thanks for taking the time to do it 🙏

I will keep this issue open and I will use it to open a PR for listing your package in the extension list. 🙌

**Comment by gsferreira** [comment]
Closed by https://github.com/Farfetch/kafkaflow/pull/344

**Pull request closed without merging**
