### PR TITLE
Adding oAuth

### PR DESCRIPTION
**Pull request by diogoabcosta89**
# Description

Adding oAuth layer to communicate to confluent kafka.

Fixes # (issue)

https://github.com/Farfetch/kafkaflow/issues/417

## How Has This Been Tested?

Created a client and secret and tested with the same IDP configured in kafka.

## Checklist

-   [x ] My code follows the style guidelines of this project
-   [x ] I have performed a self-review of my own code
-   [ ] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

**Comment by robertcoltheart** [comment]
This is going to clash with #495

**Comment by fasazevedo** [comment]
Hello Diogo!

Could you please fix the issues raised by the static code analysis? https://github.com/Farfetch/kafkaflow/pull/521/checks

We're currently in the process of reviewing and testing this PR to go forward with it. Thank you!

**Comment by robertcoltheart** [comment]
Can we somehow merge this with https://github.com/Farfetch/kafkaflow/pull/495 to support setting a token refresh handler? The use case is to be able to support AWS MSK IAM authentication which relies on this method.

**Comment by fasazevedo** [comment]
> Can we somehow merge this with #495 to support setting a token refresh handler? The use case is to be able to support AWS MSK IAM authentication which relies on this method.
> 
> Edit: I took the initiative and merged this PR to mine here: #495

Hello Robert!

Yes, the idea is to go forward with both of these PRs. We'll be validating the OAuth support first and then if everything is ok, we'll update documentation, add code samples (if needed) and then also test and go forward with your PR. 🙂

**Review by fasazevedo — APPROVED** [review]

**Review by kikofps — APPROVED** [review]

**Review by ruiqbarbosa — APPROVED** [review]

**Review by joelfoliveira — APPROVED** [review]

**Comment by fasazevedo** [comment]
Hello Diogo!

Could you please fix the commit message errors so we can merge this PR?

Thanks! 🙂

**Review by brmagadutra — APPROVED** [review]

**Pull request merged**
