### PR TITLE
docs: correct typo

### PR DESCRIPTION
**Pull request by minhtaile2712**

### CODE REVIEW

**Review by joelfoliveira — APPROVED** [review]

**Comment by joelfoliveira** [comment]
Hi @minhtaile2712 ,

Please fix the commit message: "docs: correct typo"

**Comment by minhtaile2712** [comment]
I fixed it. Please review again.

**Comment by joelfoliveira** [comment]
> I fixed it. Please review again.

The commit message was not changed and is still failing the validation. Please change the commit message.

**Comment by minhtaile2712** [comment]
I fixed it. Please review again.

**Pull request closed without merging**
